### ISSUE TITLE
Change Sidebar on Specification Pages

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#2044] opened 2024-11-19 16:49 UTC
On the current specification pages there is an "Adopt a Spec" graphic in the sidebar:

![image](https://github.com/user-attachments/assets/a3375f47-996b-4d54-af8d-45cffbd77508)

Can we please replace the the text "Adopt a Spec" with "Learn Jakarta EE" and add some text under it, "Find Starter Guides, Tutorials, and Documentation to help you get started with Jakarta EE."

Then change the learn more link to direct to the learn page: https://jakarta.ee/learn/

It should look like this:

![image](https://github.com/user-attachments/assets/279ae2c7-9d14-4836-aa78-411e6bb8c67c)

**Comment by InocencioC** [comment] 2024-12-04 14:26
Hello, I’m trying to contribute to this issue, but I’m encountering several errors when running the hugo server.

Here are the errors I’m getting:

ERROR the "date" front matter field is not a parsable date: see /home/iarmando/dev/open-source/jakarta.ee/content/compatibility/_index.ja.md
ERROR deprecated: .Site.Author was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.140.0. Implement taxonomy 'author' or use .Site.Params.Author instead.
ERROR render of "home" failed: "/home/iarmando/dev/open-source/jakarta.ee/node_modules/eclipsefdn-hugo-solstice-theme/layouts/_default/baseof.html:16:25": execute of template failed: template: index.html:16:25: executing "head" at <partial "head.html" .>: error calling partial: "/home/iarmando/dev/open-source/jakarta.ee/node_modules/eclipsefdn-hugo-solstice-theme/layouts/partials/head.html:82:4": execute of template failed: template: partials/head.html:82:4: executing "partials/head.html" at <partial "google_tag_manager.html" .>: error calling partial: execute of template failed: html/template:partials/google_tag_manager.html:10:12: no such template "_internal/google_analytics_async.html"
...

These errors are preventing me from building the site locally.

I’ve tried some solutions, such as checking the date format in the files like **![image](https://github.com/user-attachments/assets/36f74f42-6da6-49fe-aa05-aef5aa8212be)** and ensuring dependencies are up to date, but the issue persists. Could someone help me understand what might be going wrong or suggest a way to fix these errors?

Thank you in advance for your help!

**Comment by oliviergoulet5** [comment] 2024-12-04 14:37
Hi @InocencioC! It seems like your errors are caused by a mismatch in Hugo versions. 

The jakarta.ee website requires Hugo v0.110.x and Node 18.13.x.

Once you have the appropriate versions, the website should be able to build for you!

**Comment by shabnammayel** [comment] 2024-12-12 19:12
@oliviergoulet5 can you please make this change before the holidays? thanks

**Comment by oliviergoulet5** [comment] 2024-12-12 20:12
Yes, I'll make sure to have this updated before the holidays @shabnammayel

@InocencioC can you please respond if you are still interested in this issue? Otherwise, I may need to re-assign.

**Comment by InocencioC** [comment] 2024-12-13 07:53
Yes, I’m still interested, and I’ll start the development. Due to the difference in country and time zone, could you please let me know when the holiday is ?

**Comment by oliviergoulet5** [comment] 2024-12-13 13:59
@InocencioC That's great! Thanks for showing interest. This would have to be merged by December 20 before the end of our work day (4:30 PM EST).

**Comment by InocencioC** [comment] 2024-12-14 20:42
Hi @oliviergoulet5, I can´t see the "Adopt a Spec" like in this image:
![image](https://github.com/user-attachments/assets/952777a1-dbcb-495f-8c4b-0e582fbb01ba)
I search but I don´t find:
![image](https://github.com/user-attachments/assets/703e3b17-1033-47ce-b445-f8e318d1f880)
Can you help me find ?

**Comment by excentrickristy** [comment] 2024-12-14 21:03
@InocencioC you can find it on the spec pages themselves: https://jakarta.ee/specifications/platform/

**Comment by InocencioC** [comment] 2024-12-15 12:46
I try push my branch, but I dont have permission:

git push --set-upstream 
origin ChangeSideBar
remote: Permission to jakartaee/jakarta.ee.git denied to InocencioC.
fatal: unable to access 'https://github.com/jakartaee/jakarta.ee.git/': The requested URL returned error: 403

I need create a fork ?

**Comment by oliviergoulet5** [comment] 2024-12-16 15:45
@InocencioC Yes, you need to create a fork.

**Comment by InocencioC** [comment] 2024-12-16 23:36
Thanks @oliviergoulet5. I sent the PR.

**Comment by oliviergoulet5** [comment] 2024-12-17 13:58
@shabnammayel Here is a preview from @InocencioC's changes: https://deploy-preview-2066--jakartaee.netlify.app/specifications/data/

**Comment by excentrickristy** [comment] 2024-12-17 14:09
Thanks @InocencioC and @oliviergoulet5 - the orange text should just be the learn more link. Can we use white text between the title and the link similar to the image I shared?
![image](https://github.com/user-attachments/assets/a6d84576-0021-41a2-afae-b3c7b2f0acc3)

**Comment by InocencioC** [comment] 2024-12-17 16:56
I'll fix this right away, thanks for the clarification!

Done @excentrickristy.
![image](https://github.com/user-attachments/assets/346fb852-ee74-46e4-a1ae-db726e023889)

**Comment by excentrickristy** [comment] 2024-12-18 00:10
thanks @InocencioC - do you have a preview link?

**Comment by InocencioC** [comment] 2024-12-18 08:08
Hi @oliviergoulet5, could you please deploy a preview for the latest changes ?

**Comment by oliviergoulet5** [comment] 2024-12-18 14:15
Here is the link: https://deploy-preview-2068--jakartaee.netlify.app/specifications/webprofile/

@excentrickristy

**Comment by excentrickristy** [comment] 2024-12-18 22:43
Great - let's launch!

**Comment by oliviergoulet5** [comment] 2024-12-19 13:55
This is now live! Thanks @InocencioC!

**Closed as completed** 2024-12-19 13:56 UTC
