### ISSUE TITLE
updating the tutorial link to the new github page

### ISSUE THREAD

**Issue by Just-some-one** [jakartaee/jakarta.ee#1764] opened 2023-11-18 13:58 UTC
updating the tutorial link to the new github page so get used to it and be ready when version 10 tutorial finalized 

**To Reproduce**
1. Go to [documentation page](https://jakarta.ee/resources/#documentationl)
2. Click on 'Jakarta EE Tutorial'
3. it will open the old github page "https://eclipse-ee4j.github.io/jakartaee-tutorial/"

**Expected behavior**
it should be updated to open "https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/9.1/index.html"

**Desktop **
 - OS: [rocky linux 9.2]
 - Browser [firefox]
 - Version [e.g. 119]

thanks for your help and great work and have a nice day :)

**Comment by chrisguindon** [comment] 2023-11-20 14:51
Closing as I believe this is a duplicate of https://github.com/jakartaee/jakarta.ee/issues/1746

We have this MR ready to update that 'Jakarta EE Tutorial' link on the documentation page.

https://github.com/jakartaee/jakarta.ee/pull/1760

**Closed as completed by chrisguindon** 2023-11-20 14:51 UTC

**Comment by Just-some-one** [comment] 2023-11-20 14:55
thanks @chrisguindon
