### ISSUE TITLE
Update news page to use newsroom API

### ISSUE THREAD

**Issue by ericpoirier** [jakartaee/jakarta.ee#1321] opened 2021-11-18 20:22 UTC
@shabnammayel The News page currently shows news items that have been manually added to this website using markdown. It would be best to use the newsroom api here but we are going to lose the sidebar elements as those are meant to work with markdowns rather then API data.

Here is what it would look like without the sidebar:
https://deploy-preview-1320--jakartaee.netlify.app/news/

I agree that it looks better with the sidebar but for now we do not support sidear elements with news items coming from newsroom. We would need to write code to implement that.

Let me know if its ok if we lose the sidebar for now and implement the sidebar on a later date.

Thanks.

**Comment by ericpoirier** [comment] 2021-11-22 14:28
@shabnammayel I had a discussion with @chrisguindon about this issue and it seems like the /news page is intended to be displaying news items that was manually added to the website instead of items coming from newsroom.eclipse.org.

I think what we need to do here is better naming the /news page to make the difference between the 2 types of news.

Home page - news items from newsroom.eclipse.org
News page - manually added news items to Jakarta EE

@chrisguindon correct me if i'm wrong but I believe the /news page is displaying news related to the Working Group only and the home page is displaying all sorts of news.

I think to make it clear we should be naming the /news page according to what it's related to and the "View All" link on the home page should be renamed as well to say something link "View Working Group news" or something like that.

@shabnammayel @chrisguindon what do you think?

**Comment by chrisguindon** [comment] 2021-11-22 15:11
https://jakarta.ee/news/ => Working Groups News 

Documentation on how users can submit content to that news section:
https://github.com/jakartaee/jakarta.ee#how-to-include-a-new-entry-in-httpsjakartaeenews-section


News posted here must be submitted to the newsroom in order to display them on the website.


An option would be to display both on the homepage.

For example, Announcements would be all the posts from newsroom.eclipse.org. That would include all the posts marked as announcements and community news.


Under the news section on the homepage, we could display the news item from /news which is WG news.

**Comment by ericpoirier** [comment] 2021-11-22 15:16
That could be a good option as well. @shabnammayel any thoughts?

**Comment by chrisguindon** [comment] 2022-01-05 21:28
I spoke to @shabnammayel earlier today about this.

**My understanding of the problem is the following:**

The https://jakarta.ee/news/ page must include news items from the newsroom. 

**Solution:**

In order for a news item from https://jakarta.ee/news/  to appear on our homepage, we need someone to submit the news item to the Eclipse Newsroom. 

If we make sure that every post made to https://jakarta.ee/news/ is submitted to the newsroom, we can simply leverage our newsroom widget to fetch all the news items.

With this solution, we will end up with all the posts from jakarta.ee + newsroom in 1 single list. 

In a way, we would be reverting back to how we used to manage news in the past but we should be able to keep the styles that were contributed by the community since we can alter the template of each new item with our newsroom widget.


It's important to note that with this solution, we would lose the list of authors in the list page but they would still be available on the post page such as this one https://jakarta.ee/news/jakartaee91-plan-approved/ since this is not something that we track in the newsroom.

**Comment by dblevins** [comment] 2022-01-05 21:38
Hi All,

Simply manually submitting the posts from https://jakarta.ee/news/ to newsroom -- like any other article would be posted to newsroom -- was the agreement we had when we discussed this in the Marketing Committee.  That would allow the jakarta.ee homepage to include news links from both newsroom and jakarta.ee/news/.  It also has the benefit that news items on jakarta.ee/news/ are additionally available to the greater Eclipse community via the newsroom feed.

Is this the goal we are discussing or is there a separate goal in mind such as having https://jakarta.ee/news/ host items which are not official Jakarta EE news submitted/hosted by the Working Group to https://jakarta.ee/news/ directly?

**Comment by chrisguindon** [comment] 2022-01-05 21:49
@dblevins My understanding is that we would like to list all jakarta.ee news on the same page. At the moment, https://jakarta.ee/news/ is only showing news items that were created for this website under: https://github.com/jakartaee/jakarta.ee/tree/src/content/news

An alternative solution would be to keep https://jakarta.ee/news/ as-is and create a new page for when users want to see all the news. The URL could be something like jakarta.ee/news/all

However, my understanding is that we don't want to do since we think having 2 news pages will confuse the end-user.

**Comment by dblevins** [comment] 2022-01-05 22:34
The agreement and goal when this was created was for there to be a section on the jakarta.ee website where only official announcements made by the working group itself to be found.  Part of that was an explicit goal to not aggregate outside posts from community members, vendors, or 3rd parties.  As well to no longer host any kind of official working group announcements like releases or new members in other blogs such as blogs.eclipse.org -- they would be hosted on jakarta.ee and submitted via newsroom.  There's a slide deck with these items are explicitly listed in the non-goals. 

If we start aggregating 3rd party news that is not an official working group announcement or return to hosting working group announcements outside jakarta.ee, we're greatly diverging from the agreed goals.

We did have a goal that wasn't executed yet to create a jakarta.ee/blogs/ feed that did aggregate external blogs.  Having newsroom items feed into that would definitely fit with what has been agreed.

If we wanted to do anything else, we'd probably need to discuss it in the marketing committee and come to a new agreement.

**Comment by chrisguindon** [comment] 2022-01-06 02:21
@dblevins It will still be possible for the Working Group to post/submit articles under jakarta.ee/news/. My proposal will not change that.

I am not sure what you mean by 3rd party news since all news items are moderated by the Eclipse Foundation Marketing team. 

My understanding of the current issue is that we have a news section on our homepage. Under that section, we have a link to view all news which leads to https://jakarta.ee/news/

However, https://jakarta.ee/news/ is not a representation of all the jakarta news. It's missing some items that we currently include on our homepage. Which makes the View All news link misleading to the end user.

I was asked to come up with a solution to make sure that we include all the jakarta.ee news items on that page. 

I also proposed an alternative solution. That solution is simply to create 2 separate pages. One with only the content that was created on jakarta.ee and a new page that would include all the news. 

We would then update the View All News link on our homepage to lead to this new page.

In my opinion, both solutions are acceptable. It is just a question of what the community prefers.

**Comment by chrisguindon** [comment] 2022-01-06 02:31
> We did have a goal that wasn't executed yet to create a jakarta.ee/blogs/ feed that did aggregate external blogs. Having newsroom items feed into that would definitely fit with what has been agreed.

Why do you say it wasn't executed yet?

We now have a blog section on jakarta.ee which includes all the posts from jakartablogs.ee. On top of that, our solution does allow the publication of blog post articles on the working group website.

https://github.com/jakartaee/jakarta.ee/issues/1037#issuecomment-989083747
https://github.com/jakartaee/jakarta.ee/issues/1037#issuecomment-990953383

As mentioned by Eric, we don't have any blog post but in theory, the functionality does exist.

Finally, I did mention on that issue that there is still some work to be done in Q1 to get this right.

https://github.com/jakartaee/jakarta.ee/issues/1037#issuecomment-994804494

> I tend to agree with Eric. Our focus this quarter was finding a way to display blogs on jakartablogs.ee on jakarta.ee. However, there is still a lot of work to be done with blogs next quarter.
> 
> We need to define guidelines and process to enable staff and community members for submitting a blog post on jakarta.ee. At the same time, we could look at improving the list of blogs.

**Comment by chrisguindon** [comment] 2022-01-06 15:43
@ericpoirier Can you make sure we have a bug created to track the remaining changes that we need to do to enable the community/staff to post blog posts please?

We need to define guidelines and processes to enable staff and community members for submitting a blog post on jakarta.ee.

**Comment by shabnammayel** [comment] 2022-01-21 16:32
After reading the comments above, I think the announcement section is a better fit for the current content that is published on  https://jakarta.ee/news/. The goal of the current announcement section on the homepage is to list only all the official working group announcement such as new releases or new WG members. and the goal of the News section of the website is to list all community member news. 

And currently we seem to have the same problem for both sections. the "view all" link on the announcement section as well as the News section of homepage both go to https://jakarta.ee/news/ . So we need to create a page to list all announcement coming from the newsroom as well. 

My suggestion is to go with Chris's recommendation above:
"Solution:

In order for a news item from https://jakarta.ee/news/ to appear on our homepage, we need someone to submit the news item to the Eclipse Newsroom.

If we make sure that every post made to https://jakarta.ee/news/ is submitted to the newsroom, we can simply leverage our newsroom widget to fetch all the news items.

With this solution, we will end up with all the posts from jakarta.ee + newsroom in 1 single list.
In a way, we would be reverting back to how we used to manage news in the past but we should be able to keep the styles that were contributed by the community since we can alter the template of each new item with our newsroom widget."
 

However, move the current content on https://jakarta.ee/news/  to https://jakarta.ee/announcements/ to be more consistent with the goals mentioned. but the process and solution would be the same as Chris mentioned. 

We still need to create a page for "view all" of the News section with the same mechanism, but the content should be open to the wider community which is the current content on the News section of the homepage coming from newsroom

**Comment by Dexmaster** [comment] 2022-01-24 16:45
I believe there is small misunderstanding in few points

> However, move the current content on https://jakarta.ee/news/ to https://jakarta.ee/announcements/ to be more consistent with the goals mentioned. but the process and solution would be the same as Chris mentioned.

Originally it was named announcements but was migrated to news to provide same functionality to workgroup to add articles too, announcements could be a category/section in news. (P.S. I have checked PR #879, the reason it was moved to news `The consensus is that "announcements" will be rebranded as "news"`)

> If we make sure that every post made to https://jakarta.ee/news/ is submitted to the newsroom, we can simply leverage our newsroom widget to fetch all the news items.

You can show news posts on main page even now if you check sidebar at https://jakarta.ee/news/ it has latest news published. Additionally if needed you can tweak amount of articles and some category that should be shown on main page. But you don't need to submit them to newsroom to work, it just needs to be used.

**Comment by cesarhernandezgt** [comment] 2022-01-27 19:57
Hi @shabnammayel  @ericpoirier @chrisguindon @Dexmaster 

After looking at what others are doing with this like the docker page: https://www.docker.com/company/newsroom [1], the following is a proposal to allow even more unification (between announcements and nes from newsroom API) from a UI point of view and don't sacrifice functionality was already agreed in the /news page and also kept the newsroom API working.

1. In https://jakarta.ee/, the widget ANNOUCEMENTS should match the content from  https://jakarta.ee/news
2. In https://jakarta.ee/, the widget NEWS can be renamed to "In the news" since this only redirects to external websites (including eclipse domains). 
3. New page called https://jakarta.ee/in-the-news  can be created to aggregate all the submissions from the newsroom API. I couldn't find a page that summarise all the content submitted via newsroom API, so this can be an opportunity to have it.
4. If step 3 is not an option, then we can have a new page https://jakarta.ee/newsroom containing Tabs for Annoucements(AKA news) and the news from the newsroom API.

Pros: Current links are preserved and naming conventions stay as they are
Cons: Creation of 1 or two new pages to aggregate the content.

[1]
![image](https://user-images.githubusercontent.com/1454523/151430863-59736c2d-0ca7-43d4-b4c0-e614943a898f.png)

**Comment by chrisguindon** [comment] 2022-01-28 17:07
As a reminder, the problem that we are trying to solve is the following:

The **view all** news link on our homepage links to a page with only a subset of all our Jakarta news: https://jakarta.ee/news/

That's not correct. Users are expecting a page that includes all news related to jakarta.ee. 

https://jakarta.ee/news/ used to be a page with all our news but there was a consensus to replace our existing page with the new "Announcements section" : https://github.com/jakartaee/jakarta.ee/pull/879#issuecomment-791122457

> ... The consensus is that "announcements" will be rebranded as "news", so we should move the section from jakarta.ee/announcements/ to jakarta.ee/news/. There is a page at /news/ already, we can delete that and replace that section. I also notice there's a relative URL bug in the 'See all announcements' link at the bottom of each post, so we should fix that while we're at it.

I personally don't agree with this decision but that's in the past. My understanding of the pushback on this issue is that some people feel strongly about keeping /news as-is.

To help me better understand, how did we come to this consensus? Was this a decision made in the Marketing Committee call?

Since that consensus, we started to work on a big website redesign project where we made several decisions to change existing URLs to improve the site architecture.  I don't think the news section is any different than any other section of the site.

## How do we solve this?

Option A: We create new pages to break down news items per category/type:

- /news (This page would include all of jakarta.ee news. Since all of the news already exist in our newsroom, we would leverage our newsroom widget for that page. With option B, I am proposing the same solution without creating the following sub-pages)
- /news/working-group-news (This would be a list of all the WG news. Basically what we currently see on https://jakarta.ee/news/)
- /news/announcements (This is a list of news Announcements )
- /news/community-news (This is a list of Community News )

When someone submits a news item in the newsroom they need to pick a type:

![Screenshot 2022-01-28 114040](https://user-images.githubusercontent.com/893942/151586509-de5f1795-be1b-4d1f-8223-9ccc7967de7e.jpg)

Option B: We simply update /news to include all news items from the newsroom. This  was my proposal from https://github.com/jakartaee/jakarta.ee/issues/1321#issuecomment-1006091480

Option C:
We create new pages as suggested in Option A but we keep /news as-is. I think that's what the people in this issue are asking that we do.  It was suggested that we create https://jakarta.ee/in-the-news  and https://jakarta.ee/newsroom.  This means that we would be creating new top-level sections for what are essentially news items.  I think the site structure would make more sense if all our news and sub-news page were under 1 top-level section called /news.

All in all, I think we are mostly on the same page. I believe we simply don't agree with what we should do with /news. From a site architecture perspective, it makes a lot of sense to me if we show all our news under /news and create sub-pages for each category (news/announcement, news/community-news, news/working-groups).

Personally, I am not even convinced we need to create these sub-pages but I am making the suggestion since many believe our users are looking for a breakdown of all our different news types (community-news, announcements and working group news). I can understand that.

**Comment by chrisguindon** [comment] 2022-03-10 19:08
Update:

We had a meeting today with the Jakarta EE Marketing Committee to discuss this topic and we agreed to address this issue in 4 phases:

1. First priority, fix the view all news page by migrating current articles to the newsroom + install our newsroom widget. The layout of news items should stay the same. I think we can change the title of that page to "JAKARTA EE NEWS".

2. Discuss and define with mkt committee which article should be hosted on [jakarta.ee](http://jakarta.ee/) and define an internal process for making that work

3. Improve the submit news link by creating a new page that explains the 2 different workflows (newsroom vs pr/issue for posting on [jakarta.ee](http://jakarta.ee/)). We will need some content for this.

4. Once we are done with 1,2 and 3, we can look at Improving the process for submitting news by installing Netlify CMS or a similar tool on the site. I did a demo of Netlify CMS and it was well received by the committee.

@ericpoirier can you start with item 1 when you have a moment!

**Comment by ericpoirier** [comment] 2022-03-24 15:34
@chrisguindon please review the following News page:

https://deploy-preview-1432--jakartaee.netlify.app/news/

I did the changes that we talked about a few weeks ago.

Let me know if I missed anything and if you'd like to make more changes.

Thanks.

**Comment by chrisguindon** [comment] 2022-03-24 18:43
LGTM - However, I think I would show 10 items per page instead of 5. Can you update that please?

@shabnammayel @TanjaObradovic WDYT?

**Comment by chrisguindon** [comment] 2022-03-24 18:43
@ericpoirier I just noticed that clicking back to page 1 returns an empty page.

**Comment by ericpoirier** [comment] 2022-03-25 15:31
@chrisguindon I updated the news page on staging so that it shows 10 items per page and also fixed the pagination.

https://deploy-preview-1432--jakartaee.netlify.app/news/

**Comment by chrisguindon** [comment] 2022-03-25 15:35
Thanks @ericpoirier 

Could we add a scroll back to the top of the page, when the user clicks on the pagination menu? It feels a bit odd that I need to scroll up when changing pages.

**Comment by ericpoirier** [comment] 2022-03-25 15:38
> Thanks @ericpoirier
> 
> Could we add a scroll back to the top of the page, when the user clicks on the pagination menu? It feels a bit odd that I need to scroll up when changing pages.

Yeah, I can look into that.

**Comment by shabnammayel** [comment] 2022-03-28 12:28
The author for some of the articles is not reflected right. for example the latest one's author is Tanja but Jacob's name is mentioned as the author. can we fix that @ericpoirier

**Comment by ericpoirier** [comment] 2022-03-28 12:32
> The author for some of the articles is not reflected right. for example the latest one's author is Tanja but Jacob's name is mentioned as the author. can we fix that @ericpoirier

Hi @shabnammayel, we created an "Author(s)" field for the News items in the Newsroom. This is where you will need to specify who is the Author of the articles. For now, since this field is empty, the News API is picking up the person who created the News item in the Newsroom.

**Comment by ericpoirier** [comment] 2022-03-29 15:55
@shabnammayel @TanjaObradovic please review the following News page:

https://deploy-preview-1432--jakartaee.netlify.app/news/

I added the scroll to top animation as requested by @chrisguindon which was reviewed and approved by him.

I'll wait for your +1 to merge to production.

Thanks.

**Comment by cesarhernandezgt** [comment] 2022-04-04 17:57
Hi @ericpoirier

From the following [screenshot] I took from the deploy preview from the previous comment I have the following questions:

1. How can a user filter to see only the Working Group-related news? 

2. The Right side panel containing `Tags, Archive order by year` was removed in the proposal. Does this Right Side panel was also removed from the content of a post when someone clicks the `Continue reading` link? 

3. Does the Image Card functionality was also removed? in the [screenshot], cards like the one from the post `Take the 2022 Jakarta EE developer Survey Today!` no longer appear in the /news page the PR is proposing. From @ericpoirier [comment](https://github.com/jakartaee/jakarta.ee/issues/1321#issuecomment-1064398583) reflects what we discussed in the Marketing Committee call about "The layout of news items should stay the same." 


[Screenshot]
![image](https://user-images.githubusercontent.com/1454523/161600057-0529bda1-1f72-445b-92d0-859f9a14f8d8.png)

**Comment by chrisguindon** [comment] 2022-04-07 14:42
> 1. How can a user filter to see only the Working Group-related news?

The newsroom API allows us to fetch WG **Announcements** and **Community news**. +1 for adding a filter on the page that allows us to filter news items. The default should be all but there should be an option to view only WG Announcements or Community News.

> 2. The Right side panel containing Tags, Archive order by year was removed in the proposal. Does this Right Side panel was also removed from the content of a post when someone clicks the Continue reading link?

+1 For adding a sidebar on the Continue reading link page.  There should be a link at the end of the list to view all news. However, I think it's redundant to show those links on the news landing page.

@ericpoirier I am thinking that we should include the latest 10 news items in the sidebar.

> 3. Does the Image Card functionality was also removed?

We should be able to specify an image per news item. @ericpoirier I assume this is simply something we forgot to include?

Let me know if you have any questinos!

**Comment by chrisguindon** [comment] 2022-05-17 13:30
Hi All,

The latest version is on staging:

- https://deploy-preview-1432--jakartaee.netlify.app/ (homepage)
- https://deploy-preview-1432--jakartaee.netlify.app/news/ (news section)
- https://deploy-preview-1432--jakartaee.netlify.app/news/even-closer-to-jakarta-ee-10/ (article example)

If there aren't any objections, I would like to make this live this week! //cc @ericpoirier

**Comment by chrisguindon** [comment] 2022-06-03 14:44
//cc @shabnammayel @TanjaObradovic shall we go live with this? See my previous comment..

**Comment by shabnammayel** [comment] 2022-06-03 15:07
LGTM! thanks @chrisguindon

**Comment by cesarhernandezgt** [comment] 2022-06-07 18:50
Thank you all for the hard work done so far. I notice in the preview links shared by @chrisguindon that some authors' images and names in the `/news` list   don't match with the actual authors from the articles like `/news/even-closer-to-jakarta-ee-10/ (article example)`

![image](https://user-images.githubusercontent.com/1454523/172459365-37b3ee6f-1f90-42f7-be6f-9cae4a9fa3ab.png)

**Comment by ericpoirier** [comment] 2022-06-08 13:53
@cesarhernandezgt I had to manually update the author and date in the newsroom as the data over there was not the same.

@shabnammayel I took the time to look at the news items that we have on production:
https://jakarta.ee/news/

And make the date and author changes in newsroom where it was needed.

It will be important in the future to pay attention to that information and make sure it is accurate with what is on Jakarta EE.

You can see now that the dates and authors have been changed on staging:
https://deploy-preview-1432--jakartaee.netlify.app/news/

Let me know if there's anything else.

Thanks.

**Comment by cesarhernandezgt** [comment] 2022-06-08 16:57
thank you @ericpoirier for the fix 👍

**Comment by Dexmaster** [comment] 2022-06-08 22:32
@ericpoirier Just a general question do we lose tags functionality with this update? Or is that filter block? (if so how authors could add new tags/categories/filters there?)
![image](https://user-images.githubusercontent.com/6061000/172728622-b7d93357-933a-4703-a689-4c976972ab08.png)

I see @chrisguindon mentioned that we don't care for articles there but, I feel that the sidebar looks empty, some posts like announcements might be useful to be always visible in the sidebar, as they might be on the third page between other news, but stay visible in the sidebar. Also, I believe tags as filtering buttons (and not select box) will be used more/more useful.

![image](https://user-images.githubusercontent.com/6061000/172727703-90e129b0-2211-4ed5-bf28-1dd684764b4b.png)

**Comment by ericpoirier** [comment] 2022-06-09 13:11
@Dexmaster I believe it's possible to add Tags in the sidebar as the information is available in the API.

https://newsroom.eclipse.org/api/news

That being said, I would suggest we implement the tags in a separate issue so that we can move forward with what we currently have. 

Let me know what you think.

Thanks.

**Comment by shabnammayel** [comment] 2022-06-13 15:34
LGTM! thanks Eric!

**Closed as completed** 2022-06-13 15:48 UTC
