### ISSUE TITLE
About resources page refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1143] opened 2021-05-06 17:42 UTC
A simple custom page will be needed for the resources page that separates the different sections into bordered boxes with an icon, a heading, a list, and an optional link. An example of how we could author this content can be seen on the [IoT resources page](https://iot.eclipse.org/community/resources/). While it needs a reskin, it does much of what this section will need to do.

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585119
![image](https://user-images.githubusercontent.com/23018241/117341720-79ebd180-ae70-11eb-8a68-091b22f5f301.png)

**Comment by meKokabi** [comment] 2021-10-26 12:55
![image](https://user-images.githubusercontent.com/75500459/138882885-ec88f643-f491-466b-8b5c-92f7598211c2.jpg)
![FC64DC4BEB915A7B](https://user-images.githubusercontent.com/75500459/138882892-f0f73370-38b5-4756-a3f0-b6c919c4209e.jpg)

**Comment by meKokabi** [comment] 2021-10-26 13:07
Here you are the icons:
[SVG-Icons.zip](https://github.com/jakartaee/jakarta.ee/files/7418370/SVG-Icons.zip)

**Comment by ericpoirier** [comment] 2021-10-28 13:45
I created a PR to update the Resources page which you can review here:

https://deploy-preview-1298--jakartaee.netlify.app/resources/

Based on the design, there is a lot of section that we are removing, just making sure it was intended.

There is also links to them under the Resources main menu item. We should remove them if we are in fact removing all those sections.

@shabnammayel can you confirm? Thanks.

**Comment by shabnammayel** [comment] 2021-11-05 19:14
We should add all the items and links that we have under the resources navigation bar in this page actually. this mock up was before we make updates to the navigation and dropdown. thanks

**Comment by shabnammayel** [comment] 2021-11-05 19:18
Infographics is missing from this new mockup as well. Please add that and include the items from our live page here: https://jakarta.ee/resources/#infographics to the new design

**Comment by ericpoirier** [comment] 2021-11-05 19:19
@shabnammayel should we get @meKokabi involved to find the icons that we will need for the missing sections?

**Comment by ericpoirier** [comment] 2021-11-05 19:22
> Infographics is missing from this new mockup as well. Please add that and include the items from our live page here: https://jakarta.ee/resources/#infographics to the new design

Just to make sure I got this right. I will add Infographic to the main menu as well as in the Resource page?

**Comment by meKokabi** [comment] 2021-11-12 17:32
@ericpoirier Please find attached the new required icons both in png and svg formats:

[JakartaIcons.zip](https://github.com/jakartaee/jakarta.ee/files/7529367/JakartaIcons.zip)

**Comment by ericpoirier** [comment] 2021-11-15 13:25
> @ericpoirier Please find attached the new required icons both in png and svg formats:
> 
> [JakartaIcons.zip](https://github.com/jakartaee/jakarta.ee/files/7529367/JakartaIcons.zip)

Thanks.

**Comment by ericpoirier** [comment] 2021-11-18 15:35
@shabnammayel @meKokabi After reviewing the new icons, I noticed that they are not the same style as the original icons.

In order to move the redesign of this page faster, could we remove all the icons for now and when all the icons have been created we can add them on a later date?

Thanks.

**Comment by meKokabi** [comment] 2021-11-18 15:39
@ericpoirier @shabnammayel In order to have a consistent look we need to re-make all again. I have copied all the styling but still you may find them inconsistent. I am suggesting adding a blue  small triangle for now that goes well with Jakarta logo. Please let me know if you need me to re-create them.

**Comment by meKokabi** [comment] 2021-11-19 15:20
@ericpoirier @shabnammayel As discussed, I have re-make all the icons for better consistency. Please let me know if any has been missed.
[LineIcons.zip](https://github.com/jakartaee/jakarta.ee/files/7571178/LineIcons.zip)

**Comment by ericpoirier** [comment] 2021-11-22 20:20
@shabnammayel I updated the Resources page with the new icons the @meKokabi provided.

https://deploy-preview-1325--jakartaee.netlify.app/resources/

Let me know if you'd like to change anything else.

Thanks.

**Comment by shabnammayel** [comment] 2021-11-23 19:19
Hi @ericpoirier  under the presentations box, the content is wrong.
What you currently have is:
Presentations
- List of Projects
It should be:
Presentations
- Jakarta EE presentations
- Introducing the EFSP

Also can we change the text for Infographics to:

- 2018 Jakarta EE Developer Survey Findings 
- 2020 Jakarta EE Developer Survey Findings

**Comment by shabnammayel** [comment] 2021-11-24 14:50
looks good to me! Thanks 
@excentrickristy FYI

**Comment by shabnammayel** [comment] 2021-11-25 14:45
@ericpoirier I noticed we are missing the "Youtube Channel" and "Starter for Jakarta EE" in this page which are already in the dropdown. 

We need to remove the JakartaOne Livestream from there though. As we are moving it to the Community page. so maybe replace that box with YouTube Channel and add the text: Watch Jakarta EE Videos.  @meKokabi Can you please help with an icon for "Youtube Channel"?

The text for the "Starter for Jakarta EE": Generate Jakarta EE Maven Project with Examples. We can replace the "Starter for Jakarta EE" with the "Jakarta EE Specification Projects"box and use the current icon there.

**Comment by excentrickristy** [comment] 2021-11-25 22:15
Good catch Shabnam. The new layout of the resource page was intended to address an issue with the resource menu have external and anchored links. With the new layout, everything in the menu should also exist on the page. 

Once the boxes are all added to the page though, I would recommend re-ordering the menu items so that they match the order on the page. @shabnammayel do you think it should be alphabetical?

I also recommend adding an "Overview" link on the top of the Resource submenu that just takes you to the resource page without anchoring.

One picky thing - the icons here are using a very thin line weight which doesn't match with the icons being used across the site. I know we didn't provide icons for every single thing at the time but that could be arranged if needed.

**Comment by ericpoirier** [comment] 2021-11-26 18:01
I updated the Resources page based on feedback from @shabnammayel 
https://deploy-preview-1334--jakartaee.netlify.app/resources/

I also added an Overview link in the main menu.

As for the other changes suggested by @excentrickristy, I'll wait for a +1 from @shabnammayel.

**Comment by shabnammayel** [comment] 2021-11-29 12:30
Good point @excentrickristy  +1 to the alphabetic order. Can you then please help with the icons? The icons for the Community page and Specification page are also thin similar to these. Can you please help out with those as well @excentrickristy? thanks

**Comment by ericpoirier** [comment] 2021-12-01 15:57
Kristy just shared new icons by email.

Posting them here just to keep track of the assets that were sent for the Resources page.
[Jakarta-Icons.zip](https://github.com/jakartaee/jakarta.ee/files/7635343/Jakarta-Icons.zip)

**Comment by ericpoirier** [comment] 2021-12-01 16:11
@shabnammayel, I added the new icons that was provided by @excentrickristy in the following staging page:

https://deploy-preview-1334--jakartaee.netlify.app/resources/

Let me know if you have any questions.

I'll wait for your +1 to merge.

Thanks.

**Comment by shabnammayel** [comment] 2021-12-01 18:27
The items from my comment above are still missing. We can ignore "Youtube channel" and in fact remove it from the dropdown as well since we have the videos page under the "Community" dropdown. And I think that's going to go live soon. 
But we still need to add the "Starter for Jakarta EE" to the page. From my comment above: The text for the "Starter for Jakarta EE": Generate Jakarta EE Maven Project with Examples. We can replace the "Starter for Jakarta EE" with the "Jakarta EE Specification Projects"box and use the current icon there.

**Comment by ericpoirier** [comment] 2021-12-01 20:23
Hi @shabnammayel, I updated  the staging page based on your feedback.

https://deploy-preview-1334--jakartaee.netlify.app/resources/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment] 2021-12-02 14:50
in the JakartaOne Livestream box, please remove space between "Jakarta One" and also change "LiveStream" to "Livestream" with a small s. I have seen that in couple of other pages previously, would be great if we can fix them. 
In the Survey Box, we have "Jakarta EE"added to the 2021 version. For Consistency please add it to the previous versions as well. thanks

**Comment by ericpoirier** [comment] 2021-12-02 19:05
> in the JakartaOne Livestream box, please remove space between "Jakarta One" and also change "LiveStream" to "Livestream" with a small s. I have seen that in couple of other pages previously, would be great if we can fix them. In the Survey Box, we have "Jakarta EE"added to the 2021 version. For Consistency please add it to the previous versions as well. thanks

Those changes have been made to the following staging page:

https://deploy-preview-1334--jakartaee.netlify.app/resources/

Let me know if there's anything else.

Thanks.

**Comment by shabnammayel** [comment] 2021-12-02 20:01
LGTM! thanks @ericpoirier

**Closed as completed** 2021-12-02 20:22 UTC
Labels: redesign
