### ISSUE TITLE
Release 9.1 Updates to jakarta.ee 

### ISSUE THREAD

**Issue by karenmcnaughton** [jakartaee/jakarta.ee#1165] opened 2021-05-11 23:54 UTC
Jakarta EE Release 9.1 will be publicly announced on May 25th. As such, we need the following updates to go live for that date please.

Impact to jakarta.ee site are the following:

Compatible Products page: https://jakarta.ee/compatibility/ 
- add a new tab to the left of Jakarta EE 9 tab called "Jakarta EE 9.1"
- On this new tab, include the accepted/certified compatible products that are found here: https://github.com/eclipse-ee4j/jakartaee-platform/issues?q=is%3Aissue+9.1+label%3Acertification+is%3Aopen

Download Compatible Products page update: https://jakarta.ee/compatibility/download/
- add a new table at the top for "Jakarta EE 9.1 Platform" with featured Compatible Product releases, and under that table, also  the "Jakarta EE 9 Web Profile" table with related product releases featured as well

Jakarta 9 Release page: https://jakarta.ee/release/9/
- Update the text on top left to: "VERSION 9.1 NEW RELEASE"

Thank you !

**Comment by cesarhernandezgt** [comment] 2021-05-12 17:48
@karenmcnaughton 

About

>Jakarta 9 Release page: https://jakarta.ee/release/9/
>Update the text on top left to: "VERSION 9.1 NEW RELEASE"

By reusing and updating the https://jakarta.ee/release/9/ release page to have all the content migrated to say `9.1` aren't we going to lose the `9` historical content?

A new list of contributors related to 9.1 is been generated via https://github.com/jakartaee/jakarta.ee/issues/1159 so by reusing https://jakarta.ee/release/9/ for the 9.1 release we will end up losing the data from 9. Also, external references from the third-party websites already made to https://jakarta.ee/release/9/ content.

My proposal would be to create a new page: https://jakarta.ee/release/9.1/

**Comment by aeiras** [comment] 2021-05-12 18:01
Spot on Cesar. 
Protecting all the releases' history, especially its contributors are core and it takes into account the feature of the code in the creation of the Contributors' cards. We must never use old "PRs" to create new release pages in regards to the contributors' activity. 

New PR for 9.1 contributors is ready https://github.com/jakartaee/jakarta.ee/pull/1168. 

See you there @karenmcnaughton!

**Comment by autumnfound** [comment] 2021-05-12 18:01
> @karenmcnaughton
> 
> About
> 
> > Jakarta 9 Release page: https://jakarta.ee/release/9/
> > Update the text on top left to: "VERSION 9.1 NEW RELEASE"
> 
> By reusing and updating the https://jakarta.ee/release/9/ release page to have all the content migrated to say `9.1` aren't we going to lose the `9` historical content?
> 
> A new list of contributors related to 9.1 is been generated via #1159 so by reusing https://jakarta.ee/release/9/ for the 9.1 release we will end up losing the data from 9. Also, external references from the third-party websites already made to https://jakarta.ee/release/9/ content.
> 
> My proposal would be to create a new page: https://jakarta.ee/release/9.1/

Currently, I don't know if there is a plan to create any new content beyond the new compatible products section. We are just announcing there is a new minor version available on the current release 9 page as it stands. Until we have such content, I strongly advise against creating a new page until we have new content as it would be mostly duplicate content. This would tank our SEO for that page and make it harder to find in search results (SEs don't like duplicate content on sites and tend to promote that content less).

**Comment by cesarhernandezgt** [comment] 2021-05-12 18:45
> Currently, I don't know if there is a plan to create any new content beyond the new compatible products section. 

The [Jakarta EE 9.1 Final Release Marketing Plan](https://docs.google.com/spreadsheets/d/19bJB1E0m7kdslGhfFt5xyz0o9etrrlCVPFJwxP_B_m0/edit#gid=1354006467) currently states 

> Jakarta EE 9.1 updates will be made to the release page on jakarta.ee

But scope it's not defined.

My opinion is that we should create new content (cc @karenmcnaughton ).
If we keep things as they are right now and just change Top left text to "VERSION 9.1 NEW RELEASE" there is no way a visitor will know that Jakarta EE 9.1 is Java 11 compatible and engage participation to shape the upcoming Jakarta EE 10.

[PR ](https://github.com/jakartaee/jakarta.ee/pull/1168)for updating contributors list has been created in the vision of creating new content for 9.1 release.

By looking at the current design, the following content is a good candidate to be updated and pasted in the 9.1 specific page:

- FEATURES AND BENEFITS quotes can be updated to reflect that 9.1 is now Java 11 compatible.
- `Previous Release: Jakarta EE 8` link can be updated to `Previous Release: Jakarta EE 9` changing the corresponding URLs
- Section `Project Committer Git Repositories` numbers need to be updated.
- Videos section refers to Jakarta EE 9 release. 6 months later we can create at least a new video explaining the 9.1 release and current overall project status to allow engagement to prepare Jakarta EE 10 release.

**Comment by aeiras** [comment] 2021-05-12 18:52
@cesarhernandezgt you mention community/contributors' **quotes** to be added to features and benefits, question for you:
**why have a call to action to submit such quotes have not been sent to the WG forum yet?**

With a few others, we created the Jakarta Quote Submissions Guidelines that could be easily used in addition to git issues to such C2A. https://drive.google.com/drive/u/0/folders/1NBkijQ-LexTXwpExPTepMXxrYy5nMhto

**Comment by autumnfound** [comment] 2021-05-12 19:01
In terms of initial changes, I've got the following pages:

 https://deploy-preview-1169--jakartaee.netlify.app/compatibility/#tab-9_1
 https://deploy-preview-1169--jakartaee.netlify.app/compatibility/download/
 https://deploy-preview-1169--jakartaee.netlify.app/release/9/
 
A question I have outside of the release page (which seems like there is more discussion to be had around?)! We now have multiple Java version compatibilities. I've added multiple versions to capture the TCKs, but as its the same product its a bit hamfisted. I believe the refresh that is coming later this summer will address this, but is this a good enough solution until then?

**Comment by jeanouii** [comment] 2021-05-12 19:55
I think we I think there is a mistake with Apache TomEE on the 9.1 Web Profile compatible list
The version should be TomEE 9.0.0-M7

**Comment by jeanouii** [comment] 2021-05-12 19:56
I also think we should have the version added. For example, Glassfish has 1 version for jdk11 and another one jdk8
TomEE is only jdk11

**Comment by karenmcnaughton** [comment] 2021-05-12 21:16
Per our Marketing Committee Meeting on March 25th, [we captured meeting minutes (https://docs.google.com/document/d/1oovv6upwg086VTjysamYvpx06P0hgHJhMwB6TCn14ws/edit# )that outlined the following:
Update to web
Minor - add 9.1 to release 9 page; download page would have 9.1; compatible products would have 9.1 tab.

This was agreed upon by the Cmte members and has been actioned as such here in Github.

If there is a consensus to alter this plan, then it will need to be discussed on the meeting and agreed upon. There may be some additional requirements but for now, with the timeline of May 25th launch we need to be mindful of the dates.

**Comment by cesarhernandezgt** [comment] 2021-05-12 23:59
> Minor - add 9.1 to release 9 page; download page would have 9.1; compatible products would have 9.1 tab.

Hi @karenmcnaughton 
Yes, you are right. The above scope has three actions:

**a) add 9.1 to release 9 page**
b)download page would have 9.1
c) compatible products would have 9.1 tab.

From March 25th until now, I believe we are in good timing to review what we agreed on **a)**, and my previous comments state the concerns of losing historical data from Jakarta EE 9 release (https://jakarta.ee/release/9/). 

I'll follow up in the Jakarta EE Marketing Committee mailing list this thread so further analysis can be done over this issue along with a proposed solution that now it's available in a preview in this draft [PR](https://github.com/jakartaee/jakarta.ee/pull/1170): https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/

The following image (took from the preview) highlights in Green the changes made and in Red the pending content that a **new** https://jakarta.ee/release/9.1/ would require:

![image](https://user-images.githubusercontent.com/1454523/118058421-6ac2c300-b34b-11eb-9460-e3038e1a765c.png)
![image](https://user-images.githubusercontent.com/1454523/118058495-8928be80-b34b-11eb-88f6-3cbfc7cbd299.png)

**Comment by karenmcnaughton** [comment] 2021-05-13 14:54
Can we please also update the # of Committers on this page: https://jakarta.ee/release/9/ **to 120** (from the current 89).

**Comment by karenmcnaughton** [comment] 2021-05-13 18:13
To clarify: 31 Projects, 120 Committers, 60 GIT Repositories are the numbers for that line ^^

**Comment by autumnfound** [comment] 2021-05-13 18:28
@cesarhernandezgt are you taking care of the release page then? I can undo the minor changes around the release 9 page to allow you to take care of this without running into conflicts with my work!

**Comment by aeiras** [comment] 2021-05-13 19:24
> To clarify: 31 Projects, 120 Committers, 60 GIT Repositories are the numbers for that line ^^

Hola Karen, 60 GITs is incorrect. We need to count only the Jakarta EE Repos and exclude the EE4J repos.

**Comment by cesarhernandezgt** [comment] 2021-05-13 22:35
> To clarify: 31 Projects, 120 Committers, 60 GIT Repositories are the numbers for that line ^^

Hi @karenmcnaughton . I updated the number of the committer to 120 in the [PR](https://github.com/jakartaee/jakarta.ee/pull/1170) and preview available here: https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/
 
Image of the change: 
![image](https://user-images.githubusercontent.com/1454523/118195817-2bf34280-b409-11eb-9ecc-0974baa1a06d.png)

**Comment by cesarhernandezgt** [comment] 2021-05-13 22:42
> @cesarhernandezgt are you taking care of the release page then? I can undo the minor changes around the release 9 page to allow you to take care of this without running into conflicts with my work!

@autumnfound Yes please, thank you.
Currently `jakarta.ee/layouts/shortcodes/pages/release/9_1.html` is only missing:
A) text for the `FEATURES AND BENEFITS` section
b) Videos for the `POWERED BY PARTICIPATION` section (This is already a work in progress via https://github.com/jakartaee/jakarta.ee/issues/1172) 

Feel free to push to my PR if need it.

By the way, at this point, https://github.com/jakartaee/jakarta.ee/pull/1168 is ready to be reviewed and moved forward if applicable.  The page `9_1.html` needs that PR merged as part of the updated data.

**Comment by cesarhernandezgt** [comment] 2021-05-13 22:56
> > To clarify: 31 Projects, 120 Committers, 60 GIT Repositories are the numbers for that line ^^
> 
> Hola Karen, 60 GITs is incorrect. We need to count only the Jakarta EE Repos and exclude the EE4J repos.

Hi @aeiras , I just updated the repositories number in the PR and preview available here: https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/
I double checked the number of repos from https://github.com/jakartaee/

**Comment by aeiras** [comment] 2021-05-13 23:00
Excellent work @cesarhernandezgt, thank you! 
The Specification committee already approved last summer the move to a few of the API Jakarta repos from the EE4J repo to the Jakarta Repo you provided the link to. Sadly that approval vote has not yet been triggered nor executed by submission of the Bugzilla tickets with each Repo request asking for the WebMaster team to help with the Repo's exports.
 
Posting the 10 Repos, under EE 9.1 page will positively remind the entire WG, including the Spec committee of the work pending that hopefully gets done before EE 10. 
Repo stats and clean up are needed.  It starts by posting the factual data as listed in the project tools. :) 

-- exciting times,

**Comment by aeiras** [comment] 2021-05-14 14:43
@cesarhernandezgt días, 

based on this specification page, Jakarta has 39 projects (not including tck, web & full profile) https://jakarta.ee/specifications/

can you please adjust the PR to show the projects’ number?

**Comment by ivargrimstad** [comment] 2021-05-14 14:53
There is not a 1-1 mapping between specifications and projects. Some projects produce multiple specifications.
The page you are referring to lists specifications, not projects. The correct project count for Jakarta Spec projects is 31.

**Comment by aeiras** [comment] 2021-05-14 15:05
Hey Ivar, 

is there a way to fix the page then? 
none seems to know how many projects jkta has, from 30 to 33 to 39... 
how can we provide the information to match the website?

**Comment by cesarhernandezgt** [comment] 2021-05-14 15:59
@ivargrimstad @aeiras 
I opened https://github.com/jakartaee/jakarta.ee/issues/1177 so the number of Repositoroes and projects can be resolved for 9.1 and beyond.

**Comment by gerdogdu** [comment] 2021-05-16 21:50
Hi

> https://deploy-preview-1169--jakartaee.netlify.app/compatibility/download/

@autumnfound Can you please update ManageFish 6.1.0 download link to [https://download.managecat.com/6.1.0/managefish-fullprofile-6.1.0.zip](https://download.managecat.com/6.1.0/managefish-fullprofile-6.1.0.zip)

Thanks.
Gurkan

**Comment by ivargrimstad** [comment] 2021-05-17 15:29
> Hey Ivar,
> 
> is there a way to fix the page then?
> none seems to know how many projects jkta has, from 30 to 33 to 39...
> how can we provide the information to match the website?

@aeiras 
Number of Projects: 31
Number of Specs (without platform and web profile): 39
Number of Specs (WITH platform and web profile): 41

See #1177 for more details

**Comment by karenmcnaughton** [comment] 2021-05-17 19:15
Also can you pls confirm that this will be the URL: https://jakarta.ee/release/9.1/ ..?

It needs to be linked in the Press Release, so I need to confirm pls.

**Comment by cesarhernandezgt** [comment] 2021-05-17 21:06
> Also can you pls confirm that this will be the URL: https://jakarta.ee/release/9.1/ ..?
> 
> It needs to be linked in the Press Release, so I need to confirm pls.

Hi @karenmcnaughton 
I'm assuming the question is to me. Yes, https://jakarta.ee/release/9.1/ will be the page URL.

**Comment by cesarhernandezgt** [comment] 2021-05-18 20:44
@karenmcnaughton

After the review and help, we got from #1177 ,I just updated the Project, Specifications, and Repositories data with the latest numbers:

Live Preview: https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/

**Comment by aeiras** [comment] 2021-05-18 21:09
@cesarhernandezgt can we do anything about the wrong alignment in the page introducing the release?
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/10731224/118723791-ae517d00-b7e2-11eb-8fde-563a4d201a1e.png">

jakarta ee9 is too large.

**Comment by cesarhernandezgt** [comment] 2021-05-18 21:23
@aeiras the 9.1 pages reuse the same CSS from 9 release.

Locally I'm not able to replicate the overlapping you are sharing, I use a 1920 x 1080 resolution. What's the resolution you are using?

cc:  @autumnfound @chrisguindon  in case you know how to replicate it or have context about minimum resolution the website provides.

**Comment by aeiras** [comment] 2021-05-18 21:27
@cesarhernandezgt i am using Safari, zooming in or out shows me the same format, broken.

**Comment by autumnfound** [comment] 2021-05-19 12:54
> @cesarhernandezgt can we do anything about the wrong alignment in the page introducing the release?
> <img alt="image" width="1155" src="https://user-images.githubusercontent.com/10731224/118723791-ae517d00-b7e2-11eb-8fde-563a4d201a1e.png">
> 
> jakarta ee9 is too large.

This seems to be caused by zooming in to the point where the space allowed at the largest size no longer contains the huge text, the text breaks out and overlays over other elements. This happens for me at around 150% zoom and greater. There would have to be some reworking of elements to get this working. This wasn't an issue before as a single character would require an insane amount of zoom to take up the same space as 3 characters. We could probably fix this by either shrinking those characters or by playing around with the structure to make it break more cleanly if needed.

**Comment by aeiras** [comment] 2021-05-19 16:53
Gracias Martin for troubleshooting to recreate the issue. 
We leave issue to your expertise!

**Comment by jph152** [comment] 2021-05-21 14:28
Here is Ivar's video to add under the "Powered by Participation" section:

https://www.youtube.com/watch?v=5dWZbmsY8pA

**Comment by cesarhernandezgt** [comment] 2021-05-21 15:47
> Here is Ivar's video to add under the "Powered by Participation" section:
> 
> https://www.youtube.com/watch?v=5dWZbmsY8pA

Thanks, @jph152 for the video link. 

I updated the video section. Live Preview: https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/

Do you know if the second video described in https://github.com/jakartaee/jakarta.ee/issues/1172 will be generated too?

**Comment by aeiras** [comment] 2021-05-21 17:12
@ivargrimstad, 
It is wonderful that this release brings your short video. I wish for all future releases to welcome YOU to share & be the spoken DevRel you were hired and trusted to be. Good job with the video length and content!  👍

**Comment by cesarhernandezgt** [comment] 2021-05-21 18:28
> Gracias Martin for troubleshooting to recreate the issue.
> We leave issue to your expertise!

Hi @aeiras, we just push the fix for the issue you reported. You can test using live Preview: https://deploy-preview-1170--jakartaee.netlify.app/release/9.1/

**Comment by aeiras** [comment] 2021-05-21 18:35
how did it get fixed, Cesar? 
It looks great now, thank you! 
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/10731224/119183192-9a975800-ba28-11eb-8e3e-9f2d3fe43bdf.png">

**Comment by cesarhernandezgt** [comment] 2021-05-21 19:10
@TanjaObradovic @karenmcnaughton 
About the PR for landing page: https://github.com/jakartaee/jakarta.ee/pull/1170

- The last pending [issue](https://github.com/jakartaee/jakarta.ee/issues/1165#issuecomment-843565586) was solved in the PR. 
- The video section was also updated with the first one provided by @jph152. It's in my understanding that another video will be edited and provide it base on #1172 
- If any last-minute change is required next week, the Eclipse Foundation Dev team has push permissions over the PR. cc @autumnfound

**Comment by cesarhernandezgt** [comment] 2021-05-21 22:16
Small update.
> The video section was also updated with the first one provided by @jph152. It's in my understanding that another video will be edited and provide it base on #1172 

I just did this task via: https://github.com/jakartaee/jakarta.ee/issues/1172#issuecomment-846288682

**Comment by cesarhernandezgt** [comment] 2021-05-24 17:20
As stated in https://github.com/jakartaee/jakarta.ee/pull/1170#issuecomment-847205776

The following are also PR's related to 9.1 release that hasn't been merge yet:

Release 9.1 Updates to jakarta.ee /compatibility/download/ and /compatibility/#tab-9_1
#1169

Post Jakarta EE 9.1 Press Release to news/
#1193

**Comment by cesarhernandezgt** [comment] 2021-05-24 17:47
This is another PR @Dexmaster created with fixes for the contribution list: 
https://github.com/jakartaee/jakarta.ee/pull/1194

CC: @chrisguindon @autumnfound

**Comment by gerdogdu** [comment] 2021-05-24 18:00
@cesarhernandezgt Seems that ManageFish download link is wrong in #1169 . I added my comments to #1169 and also in here for @autumnfound

**Comment by chrisguindon** [comment] 2021-05-25 11:39
@gerdogdu I posted an update to the PR.

@ivargrimstad @TanjaObradovic Can you confirm that we are good to go with? https://github.com/jakartaee/jakarta.ee/pull/1169

**Comment by ivargrimstad** [comment] 2021-05-25 12:48
> @gerdogdu I posted an update to the PR.
> 
> @ivargrimstad @TanjaObradovic Can you confirm that we are good to go with? #1169

Yes, +1 from me

**Comment by autumnfound** [comment] 2021-05-28 14:41
I'll close this issue as the page is live, thanks everyone!

**Closed as completed by autumnfound** 2021-05-28 14:41 UTC
