### ISSUE TITLE
Header Banner Missing

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1717] opened 2023-09-12 22:57 UTC
I noticed today that these two pages are missing the blue header banner:
https://jakarta.ee/about/jesp/
https://jakarta.ee/committees/specification/guide/

While that is being fixed, could we add a global bottom margin to the inner pages header banner? Maybe 30 or 40px?
I noticed that on many pages the content is getting very close to the banner:
<img width="1190" alt="image" src="https://github.com/jakartaee/jakarta.ee/assets/73264129/6b281cf3-9573-4345-a97b-07f959d0bcd9">

**Comment by excentrickristy** [comment] 2023-09-12 23:09
Also missing the header banner: 

https://jakarta.ee/committees/specification/compatibility/
https://jakarta.ee/committees/specification/operations/
https://jakarta.ee/membership/join-us/
https://jakarta.ee/committees/specification/
https://jakarta.ee/community/developer-advocate/
https://jakarta.ee/committees/steering/brand_use_by_projects/  - this page is also missing the banner above the footer:
<img width="1380" alt="image" src="https://github.com/jakartaee/jakarta.ee/assets/73264129/fb500c00-960a-4ea4-ab0a-dc943e3ad144">

**Comment by oliviergoulet5** [comment] 2023-09-18 18:34
Thanks for the list of pages @excentrickristy.

Here is a preview of the header banners being added to the pages you listed:

- https://deploy-preview-1721--jakartaee.netlify.app/about/jesp/
- https://deploy-preview-1721--jakartaee.netlify.app/committees/specification/guide/
- https://deploy-preview-1721--jakartaee.netlify.app/committees/specification/compatibility/
- https://deploy-preview-1721--jakartaee.netlify.app/committees/specification/operations/
- https://deploy-preview-1721--jakartaee.netlify.app/committees/steering/brand_use_by_projects/
- https://deploy-preview-1721--jakartaee.netlify.app/community/developer-advocate/
- https://deploy-preview-1721--jakartaee.netlify.app/membership/join-us/

The margin problem with the header banner occurred from a bug with missing breadcrumbs. I merged a patch which fixed the margins and the missing breadcrumbs.

However I could not reproduce the featured footer (the component with the "Register for EclipseCon 2023" text) problem you had. The background is an image so it is possible it wasn't loaded due to some network problem at the time. If it is still occurring, try to clear your cache with a hard refresh.

**Comment by excentrickristy** [comment] 2023-09-18 19:03
They all look great except for https://deploy-preview-1721--jakartaee.netlify.app/community/developer-advocate/ - the banner is missing here still.

I agree, the footer issue must have been a glitch, looks good for me now!

**Comment by oliviergoulet5** [comment] 2023-09-18 19:11
Oh that's right, I forgot to mention the developer advocate page. It didn't appear to be a page in this repo when I was making the edits. 

I'll take another look tomorrow.

In the mean time I'll put the current set of pages that you've reviewed into code review so we can push live.

**Comment by oliviergoulet5** [comment] 2023-09-21 18:37
All heading banners have been pushed live, with exception to the developer advocate page.

I haven't had the time to revisit the developer advocate page but I have not forgotten about it.

**Comment by oliviergoulet5** [comment] 2023-09-27 15:33
Here is a preview for the developer advocate page: https://deploy-preview-1724--jakartaee.netlify.app/community/developer-advocate/ @excentrickristy

**Comment by excentrickristy** [comment] 2023-09-27 16:05
Looks good!

**Closed as completed** 2023-09-27 17:07 UTC
